language: cpp
os: linux
dist: xenial
compiler:
  - gcc
  - clang
env:
  - GENERATOR='Unix Makefiles'
  - GENERATOR=Ninja
addons:
  apt:
    update: true
    packages:
    - cmake
    - ninja-build
    - libkf5wallet-dev
    - help2man
script:
  - mkdir build
  - cd build
  - cmake -G "$GENERATOR" -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --target all
